# Generated by Django 3.2.9 on 2021-11-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_perf',
            field=models.CharField(choices=[('1', 'Profesional'), ('2', 'Cliente'), ('3', 'Administrador')], max_length=1),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to='accounts.profile')),
            ],
        ),
    ]
